#!/bin/sh
# cavapanel

### BEGIN INIT INFO
# Provides:          cavapanel
# Required-Start:    $syslog $remote_fs $network
# Required-Stop:     $syslog $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: jenkins
### END INIT INFO

PROGRAM=cavapanel
USER=jenkins
SCRIPT=/var/lib/jenkins/production/cavapanel/bin/cavapanel
LOG=/var/log/cavapanel.log

(echo "FYI on $(date)"; echo "production $PROGRAM $*") | mailx -s "junjible.com $*" maas-trac@chatsubo.net

# must run as jenkins
if [ "$(id -un)" = "$USER" ]; then
  logger -s -t $PROGRAM "about to execute: $SCRIPT $*"
  $SCRIPT $* >> $LOG 2>&1 &
else
  logger -s -t $PROGRAM "about to execute as jenkins: $SCRIPT $*"
  su --login --command "$SCRIPT $*" $USER >> $LOG 2>&1 &
fi
